Afegeix quota al crear grups Canvi dinamica de missatges

diff --git a/oscripts/ganesha-add-grups b/oscripts/ganesha-add-grups
--- a/oscripts/ganesha-add-grups
+++ b/oscripts/ganesha-add-grups
@@ -7,6 +7,7 @@
 #    $1="Codigo asignatura" 
 #    $2="Nom dels grups separats per espai" 
 #    $3="Nius dels professors separats per espai" 
+#    $4="quota"
 #
 #  Salida en STDOUT (no STDERR): 
 #    [
@@ -43,12 +44,14 @@
 #	517 - El directorio del grupo de la asignatura no se puede crear, motivo desconocido
 #	518 - El grupo local del grupo de la asignatura no se puede crear, motivo desconocido
 #	519 - No se han podido cambiar los permisos del directorio del grupo de la asignatura, motivo desconocido
+#	526 - La quota del grupo de la asignatura no se puede cambiar, motivo desconocido
 #	599 - Faltan parámetros
 
 source /usr/local/sbin/ganesha-config.sh
 asignatura="$1"
 grupos_asignatura="$2"
 nius_profesores="$3"
+var_quota="$4"
 
 salida()
 { 
@@ -87,6 +90,7 @@ salida()
 		if [ "$error" -lt "500" ]; then /bin/mkdir -m 2770  $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=517; fi
 		if [ "$error" -lt "500" ]; then /usr/sbin/addgroup "$grupo" 2>/dev/null 1>/dev/null || error=518; fi
 		if [ "$error" -lt "500" ]; then /bin/chown root:"$grupo" $HOME_GANESHA"/$asignatura/$grupo"  2>/dev/null 1>/dev/null || error=519; fi
+		if [ "$error" -lt "500" ]; then setquota -g "$grupo" "$var_quota" "$var_quota" 0 0 $HOME_GANESHA"/" || error=526; fi 
 
 		if  [ "$error" -lt "500" ]; then
 
diff --git a/oscripts/ganesha-lvm-info b/oscripts/ganesha-lvm-info
--- a/oscripts/ganesha-lvm-info
+++ b/oscripts/ganesha-lvm-info
@@ -18,8 +18,8 @@
 #	2.- Mostrar los datos de espacio o el error
 #
 #  Codigos de error:
-#	501 - No se ha podido encontrar los datos de espacio (1.- El filesystem no existe. 2.- Permiso denegado). 
-#	510 - Faltan parámetros
+#	528 - No se ha podido encontrar los datos de espacio del filesystem, motivo desconocido
+#	529 - No existe el directorio con el filesystem, o no está montado  
 
 source /usr/local/sbin/ganesha-config.sh
 
@@ -27,7 +27,12 @@ salida()
 {
     echo "{"
     echo "\"codi\":$2,"
-    echo "\"message\":\"$1\","
+    if [ "$2" -eq "200" ]; then
+       echo "\"message\":\"$1\","
+    else
+       codigo_error="codigo_$2"
+       echo "\"message\":\"${!codigo_error}\","
+    fi
     echo "\"json\": [ {\"volname\":\"$3\", \"espacio_total\":\"$4\", \"espacio_usado\":\"$5\", \"espacio_libre\":\"$6\"} ]" ;
     echo "}"
 }
@@ -36,11 +41,11 @@ export -f salida
 
 	error="0"
 
-	if [ $HOME_GANESHA ]; then
-		df -h "$HOME_GANESHA" 2>/dev/null 1>/dev/null || error="501"
-		df -h "$HOME_GANESHA" 2>/dev/null | grep "$HOME_GANESHA" | awk  ' { print $1" "$2" "$3" "$4 } ' |  xargs  bash -c 'salida "OK" "200" "$0" "$1" "$2" "$3"'  
+	if [ -d $HOME_GANESHA ]; then
+		df -h "$HOME_GANESHA" 2>/dev/null 1>/dev/null || error=528
+		if [ "$error" -lt "500" ]; then df -h "$HOME_GANESHA" 2>/dev/null | grep "$HOME_GANESHA" | awk  ' { print $1" "$2" "$3" "$4 } ' |  xargs  bash -c 'salida "OK" "200" "$0" "$1" "$2" "$3"'; fi
 	else
-		error="510"
+		error=529
 	fi
 
         if [ "$error" -gt "500" ]; then
