Ordenacion y tabulacion

diff --git a/oscripts/ganesha-add-alumne-grup b/oscripts/ganesha-add-alumne-grup
--- a/oscripts/ganesha-add-alumne-grup
+++ b/oscripts/ganesha-add-alumne-grup
@@ -2,21 +2,21 @@
 #
 
 #  Nombre script: ganesha-add-alumne-grup
-# 
-#  Parámetros de entrada: 
-#    $1="usuario" 
-#    $2="asignatura"
-#    $3="grupo_asignatura" 
 #
-#  Salida en STDOUT (no STDERR): 
+#  Parámetros de entrada:
+#    $1="usuario"
+#    $2="asignatura"
+#    $3="grupo_asignatura"
+#
+#  Salida en STDOUT (no STDERR):
 #    {
-#    "codi":"<codi>", 
-#    "message":"<mensaje>", 
+#    "codi":"<codi>",
+#    "message":"<mensaje>",
 #    "json": { "usuario":"<usuario>", "asignatura":"<asignatura>", "grupo_asignatura":"<grupo_asignatura>" }
 #
 #  Operaciones:
 #	1.- Asignar "usuario" al grupo "asignatura" local
-#	2.- Asignar "usuario" al grupo "grupo_asignatura" local  
+#	2.- Asignar "usuario" al grupo "grupo_asignatura" local
 #	3.- Mostrar codigo de salida correcta o incorrecta según caso.
 #
 #  Codigos de error:
@@ -34,18 +34,18 @@ asignatura="$2"
 grupo_asignatura="$3"
 
 salida()
-{ 
-    echo "{" 
-    echo "\"codi\":$2," 
-    if [ "$2" -eq "200" ]; then
-       echo "\"message\":\"$1\","
-    else
-       codigo_error="codigo_$2"
-       echo "\"message\":\"${!codigo_error}\","
-    fi
-    echo "\"json\": {\"usuario\":\"$usuario\", \"asignatura\":\"$asignatura\", \"grupo_asignatura\":\"$grupo_asignatura\"} " ; 
-    echo "}"
-} 
+{
+  echo "{"
+  echo "\"codi\":$2,"
+  if [ "$2" -eq "200" ]; then
+      echo "\"message\":\"$1\","
+  else
+      codigo_error="codigo_$2"
+      echo "\"message\":\"${!codigo_error}\","
+  fi
+  echo "\"json\": {\"usuario\":\"$usuario\", \"asignatura\":\"$asignatura\", \"grupo_asignatura\":\"$grupo_asignatura\"} " ;
+  echo "}"
+}
 
 	error="0"
 
@@ -56,33 +56,33 @@ salida()
 		if [ ! -d "$HOME_GANESHA/$asignatura" ]; then  salida "ERROR" "505"; exit ; fi
 		if [ ! -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then  salida "ERROR" "506"; exit ; fi
 		if [ ! $(getent group "$asignatura") ]; then salida "ERROR" "507"; exit; fi
-		if [ ! $(getent group "$grupo_asignatura") ]; then salida "ERROR" "508"; exit; fi 
+		if [ ! $(getent group "$grupo_asignatura") ]; then salida "ERROR" "508"; exit; fi
 
-# Fin control de errores fatales	
+# Fin control de errores fatales
 
 		if [ -d "$HOME_GANESHA/$asignatura/" ]; then
 			if [ $(getent group "$asignatura") ]; then
-				  /usr/sbin/adduser $usuario $asignatura 2>/dev/null 1>/dev/null || error=509; 
+				  /usr/sbin/adduser $usuario $asignatura 2>/dev/null 1>/dev/null || error=509;
 			else error=507;
 			fi
 
-	                if [ -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ] && [ "$error" -lt "500" ]; then
-                       	 if [ $(getent group "$grupo_asignatura") ]; then
-                                 /usr/sbin/adduser $usuario $grupo_asignatura 2>/dev/null 1>/dev/null || error=510;
-                         else error=508;
-                         fi
-                	else error=506;
-	                fi
-                else 
+      if [ -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ] && [ "$error" -lt "500" ]; then
+              if [ $(getent group "$grupo_asignatura") ]; then
+                      /usr/sbin/adduser $usuario $grupo_asignatura 2>/dev/null 1>/dev/null || error=510;
+              else error=508;
+              fi
+      else error=506;
+      fi
+    else
 			error=505;
-		fi 
-  	else
+		fi
+  else
 		error=599
 	fi
 
-        if [ "$error" -gt "500" ]; then
-             salida "ERROR" "$error"
-          else
-             salida "Usuari afegit correctament!" "200"
-        fi
+  if [ "$error" -gt "500" ]; then
+        salida "ERROR" "$error"
+    else
+        salida "Usuari afegit correctament!" "200"
+  fi
 
diff --git a/oscripts/ganesha-add-assignatura b/oscripts/ganesha-add-assignatura
--- a/oscripts/ganesha-add-assignatura
+++ b/oscripts/ganesha-add-assignatura
@@ -35,16 +35,16 @@ asignatura="$1"
 
 salida()
 {
-    echo "{"
-    echo "\"codi\":$2,"
-    if [ "$2" -eq "200" ]; then
-            echo "\"message\":\"$1\","
-        else
-            codigo_error="codigo_$2"
-            echo "\"message\":\"${!codigo_error}\","
-    fi
-    echo "\"json\": [ {\"codi_assignatura\":\"$asignatura\"} ]" ;
-    echo "}"
+  echo "{"
+  echo "\"codi\":$2,"
+  if [ "$2" -eq "200" ]; then
+          echo "\"message\":\"$1\","
+      else
+          codigo_error="codigo_$2"
+          echo "\"message\":\"${!codigo_error}\","
+  fi
+  echo "\"json\": [ {\"codi_assignatura\":\"$asignatura\"} ]" ;
+  echo "}"
 }
 
 	error="0"
@@ -54,23 +54,23 @@ salida()
 # Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són válidas de antemano
 
 		if [ ${#asignatura} -ge 15 ]; then salida "ERROR" "538"; exit; fi
-		case "$asignatura" in
-			(*[![abcdefghijklmnopqrstuvwxyz0123456789-]*) salida "ERROR" "539"; exit ;;
-		esac
-                if [ -d "$HOME_GANESHA/$asignatura" ]; then salida "ERROR" "503"; exit; fi
-                if [ $(getent group "$asignatura") ]; then salida "ERROR" "512"; exit; fi
+    case "$asignatura" in
+      (*[![abcdefghijklmnopqrstuvwxyz0123456789-]*) salida "ERROR" "539"; exit ;;
+    esac
+    if [ -d "$HOME_GANESHA/$asignatura" ]; then salida "ERROR" "503"; exit; fi
+    if [ $(getent group "$asignatura") ]; then salida "ERROR" "512"; exit; fi
 
 # Fin control de errores fatales
 
-		if [ -d "$HOME_GANESHA/$asignatura" ]; then error=503; else /bin/mkdir -m 0750  $HOME_GANESHA"/$asignatura" 2>/dev/null 1>/dev/null || error=511; fi
-		if [ "$error" -lt "500" ]; then if [ $(getent group "$asignatura") ]; then error=512; else /usr/sbin/addgroup "$asignatura" 2>/dev/null 1>/dev/null || error=502; fi; fi
-		if [ "$error" -lt "500" ]; then /bin/chown root:"$asignatura" $HOME_GANESHA"/$asignatura"  2>/dev/null 1>/dev/null || error=504; fi
-	else
-		error="599"
-        fi
+    if [ -d "$HOME_GANESHA/$asignatura" ]; then error=503; else /bin/mkdir -m 0750  $HOME_GANESHA"/$asignatura" 2>/dev/null 1>/dev/null || error=511; fi
+    if [ "$error" -lt "500" ]; then if [ $(getent group "$asignatura") ]; then error=512; else /usr/sbin/addgroup "$asignatura" 2>/dev/null 1>/dev/null || error=502; fi; fi
+    if [ "$error" -lt "500" ]; then /bin/chown root:"$asignatura" $HOME_GANESHA"/$asignatura"  2>/dev/null 1>/dev/null || error=504; fi
+  else
+    error="599"
+  fi
 
-	 if [ "$error" -gt "500" ]; then
-             salida "ERROR" "$error"
-          else
- 	     salida "Assignatura creada correctament." "200"
-	 fi
+  if [ "$error" -gt "500" ]; then
+    salida "ERROR" "$error"
+  else
+    salida "Assignatura creada correctament." "200"
+  fi
diff --git a/oscripts/ganesha-add-grups b/oscripts/ganesha-add-grups
--- a/oscripts/ganesha-add-grups
+++ b/oscripts/ganesha-add-grups
@@ -2,22 +2,22 @@
 #
 
 #  Nombre script: ganesha-add-grups
-# 
-#  Parámetros de entrada: 
-#    $1="Codigo asignatura" 
-#    $2="Nom dels grups separats per espai" 
-#    $3="Nius dels professors separats per espai" 
+#
+#  Parámetros de entrada:
+#    $1="Codigo asignatura"
+#    $2="Nom dels grups separats per espai"
+#    $3="Nius dels professors separats per espai"
 #    $4="quota"
 #
-#  Salida en STDOUT (no STDERR): 
+#  Salida en STDOUT (no STDERR):
 #    [
-#    {"codi":<codi>, 
-#    "message":"<mensaje>", 
+#    {"codi":<codi>,
+#    "message":"<mensaje>",
 #    "json": { "nomgrup":"<codi_assignatura_grup>" }
 #     },
 #     {"codi":<codi>,
 #    "message":""<mensaje>",
-#    "json": { "nomgrup":"<codi_assignatura_grup>" }, 
+#    "json": { "nomgrup":"<codi_assignatura_grup>" },
 #     },
 #     ...
 #     {"codi":<codi>,
@@ -30,7 +30,7 @@
 #	1.- Crear directorio de grupo en la asignatura en la ruta definida por "ganesha-config.sh": "$HOME_GANESHA"/"$asignatura"
 #	2.- Crear grupo local de asignatura_grupo
 #	3.- Asignar permisos directorio de asignatura_grupo
-#	4.- Asignar niu_profe a grupo local asignatura	
+#	4.- Asignar niu_profe a grupo local asignatura
 #	5.- Asignar niu_profe a grupo local asignatura_grupo
 #	6.- Mostrar codigo de salida correcta o incorrecta según caso.
 #
@@ -54,67 +54,67 @@ nius_profesores="$3"
 var_quota="$4"
 
 salida()
-{ 
-    echo "{" 
-    echo "\"codi\":$2," 
-    if [ "$2" -eq "200" ]; then
-       echo "\"message\":\"$1\","
-    else
-       codigo_error="codigo_$2"
-       echo "\"message\":\"${!codigo_error}\","
-    fi
-    echo "\"json\": { \"assignatura\":\"$asignatura\", \"nomgrup\":\"$3\" }" ; 
-    echo "},"
-} 
+{
+  echo "{"
+  echo "\"codi\":$2,"
+  if [ "$2" -eq "200" ]; then
+      echo "\"message\":\"$1\","
+  else
+      codigo_error="codigo_$2"
+      echo "\"message\":\"${!codigo_error}\","
+  fi
+  echo "\"json\": { \"assignatura\":\"$asignatura\", \"nomgrup\":\"$3\" }" ;
+  echo "},"
+}
 
-    txt_salida=""
+  txt_salida=""
 
 #    if [[ $asignatura && $grupos_asignatura && $nius_profesores ]]; then
-    if [[ $asignatura && $grupos_asignatura ]]; then
-    
-	echo "["
-    
-        for grupo in $grupos_asignatura
-           do
-                error="0"
+  if [[ $asignatura && $grupos_asignatura ]]; then
+
+	  echo "["
+
+    for grupo in $grupos_asignatura
+      do
+        error="0"
 
 # Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són validas de antemano
 
-                if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
-                if [ -d "$HOME_GANESHA/$asignatura/$grupo" ]; then error=514; fi
-                if [ ! $(getent group "$asignatura") ]; then error=507; fi
-                if [ $(getent group "$grupo") ]; then error=515; fi 
+        if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
+        if [ -d "$HOME_GANESHA/$asignatura/$grupo" ]; then error=514; fi
+        if [ ! $(getent group "$asignatura") ]; then error=507; fi
+        if [ $(getent group "$grupo") ]; then error=515; fi
 
 # Fin control de errores fatales
 
-		if [ "$error" -lt "500" ]; then /bin/mkdir -m 2770  $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=517; fi
-		if [ "$error" -lt "500" ]; then /usr/sbin/addgroup "$grupo" 2>/dev/null 1>/dev/null || error=518; fi
-		if [ "$error" -lt "500" ]; then /bin/chown root:"$grupo" $HOME_GANESHA"/$asignatura/$grupo"  2>/dev/null 1>/dev/null || error=519; fi
-		if [ "$error" -lt "500" ]; then setquota -g "$grupo" "$var_quota" "$var_quota" 0 0 $HOME_GANESHA"/" || error=526; fi 
+        if [ "$error" -lt "500" ]; then /bin/mkdir -m 2770  $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=517; fi
+        if [ "$error" -lt "500" ]; then /usr/sbin/addgroup "$grupo" 2>/dev/null 1>/dev/null || error=518; fi
+        if [ "$error" -lt "500" ]; then /bin/chown root:"$grupo" $HOME_GANESHA"/$asignatura/$grupo"  2>/dev/null 1>/dev/null || error=519; fi
+        if [ "$error" -lt "500" ]; then setquota -g "$grupo" "$var_quota" "$var_quota" 0 0 $HOME_GANESHA"/" || error=526; fi
 
-		if  [ "$error" -lt "500" ]; then
+        if  [ "$error" -lt "500" ]; then
 
-			for niu_profe in $nius_profesores
-			 do
-			   error=0
-			   /usr/sbin/adduser $niu_profe $asignatura 2>/dev/null 1>/dev/null || error=513
-			   if [ "$error" -lt "500" ]; then /usr/sbin/adduser $niu_profe $grupo 2>/dev/null 1>/dev/null || error=516; fi
-			 done
-		fi	
+          for niu_profe in $nius_profesores
+          do
+            error=0
+            /usr/sbin/adduser $niu_profe $asignatura 2>/dev/null 1>/dev/null || error=513
+            if [ "$error" -lt "500" ]; then /usr/sbin/adduser $niu_profe $grupo 2>/dev/null 1>/dev/null || error=516; fi
+          done
+		    fi
 
      	  if [ "$error" -gt "500" ]; then
-	     txt_salida="$txt_salida$(salida "ERROR" "$error" "$grupo")" 
-	  else 
-	     txt_salida="$txt_salida$(salida "El grup de l'assignatura s'ha creat correctament." "200" "$grupo")"
-	  fi
-        done
+	        txt_salida="$txt_salida$(salida "ERROR" "$error" "$grupo")"
+	      else
+	        txt_salida="$txt_salida$(salida "El grup de l'assignatura s'ha creat correctament." "200" "$grupo")"
+	      fi
+      done
 
-     else  
-                error="599"
-		txt_salida=$(salida "ERROR" "$error")
-     fi 
+  else
+    error="599"
+    txt_salida=$(salida "ERROR" "$error")
+  fi
 
-        txt_salida=${txt_salida::-1}
-        echo "$txt_salida"
-        echo "]"
+  txt_salida=${txt_salida::-1}
+  echo "$txt_salida"
+  echo "]"
 
diff --git a/oscripts/ganesha-add-profe-assignatura b/oscripts/ganesha-add-profe-assignatura
--- a/oscripts/ganesha-add-profe-assignatura
+++ b/oscripts/ganesha-add-profe-assignatura
@@ -30,41 +30,42 @@ asignatura="$2"
 
 salida()
 {
-    echo "{"
-    echo "\"codi\":$2,"
-    if [ "$2" -eq "200" ]; then
-	    echo "\"message\":\"$1\","
-	else
-	    codigo_error="codigo_$2"
-            echo "\"message\":\"${!codigo_error}\","
-    fi
-    echo "\"json\": [ {\"usuario\":\"$usuario\"}, {\"asignatura\":\"$asignatura\"} ]" ;
-    echo "}"
+  echo "{"
+  echo "\"codi\":$2,"
+  if [ "$2" -eq "200" ]; then
+    echo "\"message\":\"$1\","
+  else
+    codigo_error="codigo_$2"
+    echo "\"message\":\"${!codigo_error}\","
+  fi
+  echo "\"json\": [ {\"usuario\":\"$usuario\"}, {\"asignatura\":\"$asignatura\"} ]" ;
+  echo "}"
 }
 
 	error=0
 
 	if [[ $usuario && $asignatura ]]; then
-	    if [ $(getent group "$asignatura") ]; then
+	  if [ $(getent group "$asignatura") ]; then
+
 		/usr/sbin/adduser $usuario $asignatura 2>/dev/null 1>/dev/null || error=513
 
-                if [ "$error" -lt "500" ] && [ -d "$HOME_GANESHA/$asignatura" ]; then
-                   cd $HOME_GANESHA"/$asignatura"
-			for directorio_grupo in  $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do
-			  /usr/sbin/adduser $usuario $directorio_grupo 2>/dev/null 1>/dev/null || error=516;
-			done
-                fi
+      if [ "$error" -lt "500" ] && [ -d "$HOME_GANESHA/$asignatura" ]; then
+        cd $HOME_GANESHA"/$asignatura"
+        for directorio_grupo in  $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do
+          /usr/sbin/adduser $usuario $directorio_grupo 2>/dev/null 1>/dev/null || error=516;
+        done
+      fi
 
-	    else
-	        error=507
-	    fi
+    else
+        error=507
+    fi
   	else
 		error=599
 	fi
 
-        if [ "$error" -gt "500" ]; then
-             salida "ERROR" "$error"
-          else
-	      salida "Añadido el profesor a la asignatura" "200"
-        fi
+  if [ "$error" -gt "500" ]; then
+        salida "ERROR" "$error"
+    else
+  salida "Añadido el profesor a la asignatura" "200"
+  fi
 
diff --git a/oscripts/ganesha-del-alumnes-grup b/oscripts/ganesha-del-alumnes-grup
--- a/oscripts/ganesha-del-alumnes-grup
+++ b/oscripts/ganesha-del-alumnes-grup
@@ -2,23 +2,23 @@
 #
 
 #  Nombre script: ganesha-del-alumnes-grup
-# 
-#  Parámetros de entrada: 
-#    $1="usuario" 
+#
+#  Parámetros de entrada:
+#    $1="usuario"
 #    $2="asignatura"
-#    $3="grupo_asignatura" 
+#    $3="grupo_asignatura"
 #    $4="vaciar_grupo" (TRUE/Cualquier otro valor diferente de "TRUE" será falso)
 #
-#  Salida en STDOUT (no STDERR): 
+#  Salida en STDOUT (no STDERR):
 #    {
-#    "codi":"<codi>", 
-#    "message":"<mensaje>", 
+#    "codi":"<codi>",
+#    "message":"<mensaje>",
 #    "json": { "usuario":"<usuario>", "asignatura":"<asignatura>", "grupo_asignatura":"<grupo_asignatura>" }
 #     }
 #
 #  Operaciones:
 #	1.- Borrar "usuario" del grupo "grupo_asignatura" local
-#	2.- Borrar "usuario" al grupo "asignatura" local  
+#	2.- Borrar "usuario" al grupo "asignatura" local
 #	3.- Mostrar codigo de salida correcta o incorrecta según caso.
 #
 #  Codigos de error:
@@ -38,69 +38,67 @@ grupo_asignatura="$3"
 vaciar_grupo="$4"
 
 salida()
-{ 
-    echo "{" 
-    echo "\"codi\":\"$2\"," 
+{
+    echo "{"
+    echo "\"codi\":\"$2\","
     if [ "$2" -eq "200" ]; then
        echo "\"message\":\"$1\","
     else
        codigo_error="codigo_$2"
        echo "\"message\":\"${!codigo_error}\","
     fi
-    echo "\"json\": {\"usuario\":\"$3\", \"asignatura\":\"$4\", \"grupo_asignatura\":\"$5\"}" ; 
+    echo "\"json\": {\"usuario\":\"$3\", \"asignatura\":\"$4\", \"grupo_asignatura\":\"$5\"}" ;
     echo "},"
-} 
+}
 
 
  echo "["
 
 	error="0"
-	
+
 	if [[ $usuarios && $asignatura && $grupo_asignatura ]]; then
 
 	  for usuario in $usuarios
-              do
-                error="0"
+      do
+        error="0"
 
 # Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són validas de antemano
 
-               if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
-               if [ ! -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then error=506; fi
-               if [ ! $(getent group "$asignatura") ]; then error=507; fi
-               if [ ! $(getent group "$grupo_asignatura") ]; then error=508; fi
+        if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
+        if [ ! -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then error=506; fi
+        if [ ! $(getent group "$asignatura") ]; then error=507; fi
+        if [ ! $(getent group "$grupo_asignatura") ]; then error=508; fi
 
 # Fin control de errores fatales
+        if [ "$error" -lt "500" ]; then /usr/sbin/deluser $usuario $grupo_asignatura 2>/dev/null 1>/dev/null || error=520; fi
+        if [ "$error" -lt "500" ] && [ "$(grep $asignatura /etc/group | grep $usuario | wc -l)" -lt "2" ] ; then
+          /usr/sbin/deluser $usuario $asignatura 2>/dev/null 1>/dev/null || error=521
+        fi
 
-
-		if [ "$error" -lt "500" ]; then /usr/sbin/deluser $usuario $grupo_asignatura 2>/dev/null 1>/dev/null || error=520; fi 
-		if [ "$error" -lt "500" ] && [ "$(grep $asignatura /etc/group | grep $usuario | wc -l)" -lt "2" ] ; then
- 			/usr/sbin/deluser $usuario $asignatura 2>/dev/null 1>/dev/null || error=521
-		 fi
-
-        	if [ "$error" -gt "500" ]; then
-	             txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuario" "$asignatura" "$grupo_asignatura")"
-	          else
-	             txt_salida="$txt_salida$(salida "OK" "200" "$usuario" "$asignatura" "$grupo_asignatura")"
-	        fi
+        if [ "$error" -gt "500" ]; then
+              txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuario" "$asignatura" "$grupo_asignatura")"
+          else
+              txt_salida="$txt_salida$(salida "OK" "200" "$usuario" "$asignatura" "$grupo_asignatura")"
+        fi
 
 	  done
-	
-	 if [ "$vaciar_grupo" = "TRUE" ] && [ "$error" -lt "500" ]; then
-		if [ -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then
-		   /bin/rm -rf "$HOME_GANESHA/$asignatura/$grupo_asignatura/"* 2>/dev/null 1>/dev/null || error=537;
-		   if [ "$error" -gt "500" ]; then
-			 txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuarios" "$asignatura" "$grupo_asignatura")"
-		   fi
-		fi
- 	 fi
 
-  	else
+    if [ "$vaciar_grupo" = "TRUE" ] && [ "$error" -lt "500" ]; then
+      if [ -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then
+        /bin/rm -rf "$HOME_GANESHA/$asignatura/$grupo_asignatura/"* 2>/dev/null 1>/dev/null || error=537;
+        if [ "$error" -gt "500" ]; then
+        txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuarios" "$asignatura" "$grupo_asignatura")"
+        fi
+      fi
+    fi
+
+  else
 		error=599
 		txt_salida=$(salida "ERROR" "$error")
 	fi
 
 
-    txt_salida=${txt_salida::-1}
-    echo "$txt_salida"
-    echo "]"
+  txt_salida=${txt_salida::-1}
+  echo "$txt_salida"
+  echo "]"
 
diff --git a/oscripts/ganesha-del-grups b/oscripts/ganesha-del-grups
--- a/oscripts/ganesha-del-grups
+++ b/oscripts/ganesha-del-grups
@@ -2,23 +2,23 @@
 #
 
 #  Nombre script: ganesha-del-grups
-# 
-#  Parámetros de entrada: 
-#    $1="Codi d’assignatura" 
-#    $2="Nom dels grups separats per espai" 
+#
+#  Parámetros de entrada:
+#    $1="Codi d’assignatura"
+#    $2="Nom dels grups separats per espai"
 #    $3="Forzar borrado(TRUE/Cualquier otro valor diferente de "TRUE" será falso)"
 #
-#  Salida en STDOUT (no STDERR): 
+#  Salida en STDOUT (no STDERR):
 #    [
 #    {
-#    "codi":<codi>, 
-#    "message":"<mensaje>", 
+#    "codi":<codi>,
+#    "message":"<mensaje>",
 #    "json": { "nomgrup":"<codi_assignatura_grup>" }
 #    },
 #    {
 #    "codi":<codi>,
 #    "message":"<mensaje>,
-#    "json": { "nomgrup":"<codi_assignatura_grup>" }, 
+#    "json": { "nomgrup":"<codi_assignatura_grup>" },
 #    },
 #    ...
 #    {
@@ -49,22 +49,22 @@ grupos_asignatura="$2"
 forzar_borrado="$3"
 
 salida()
-{ 
-    echo "{" 
-    echo "\"codi\":$2," 
-    if [ "$2" -eq "200" ]; then
-       echo "\"message\":\"$1\","
-    else
-       codigo_error="codigo_$2"
-       echo "\"message\":\"${!codigo_error}\","
-    fi
-    echo "\"json\": {\"asignatura:\":\"$asignatura\",\"nomgrup\":\"$3\"}" ; 
-    echo "},"
-} 
+{
+  echo "{"
+  echo "\"codi\":$2,"
+  if [ "$2" -eq "200" ]; then
+      echo "\"message\":\"$1\","
+  else
+      codigo_error="codigo_$2"
+      echo "\"message\":\"${!codigo_error}\","
+  fi
+  echo "\"json\": {\"asignatura:\":\"$asignatura\",\"nomgrup\":\"$3\"}" ;
+  echo "},"
+}
 
-   echo "["
+  echo "["
 
-   if [[ $asignatura && $grupos_asignatura ]]; then
+  if [[ $asignatura && $grupos_asignatura ]]; then
 
     for grupo in $grupos_asignatura
       do
@@ -79,29 +79,29 @@ salida()
        if [ ! $(getent group "$grupo") ]; then error=508; fi
 
 # Fin control de errores fatales
-       
-       if [ "$error" -lt "500" ]; then
-	if [ "$forzar_borrado" = "TRUE" ]; then 
-		/bin/rm -rf $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=536;
-	  else
-		/bin/rmdir $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=536;	
-	fi
-	
-	if [ "$error" -lt "500" ]; then setquota -g "$grupo" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error=531; fi
-	if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$grupo" 2>/dev/null 1>/dev/null || error=532; fi
-       fi
-	
-	if [ "$error" -gt "500" ]; then
-	     txt_salida="$txt_salida$(salida "ERROR" "$error" "$grupo")"
-	  else 
-	     txt_salida="$txt_salida$(salida "OK" "200" "$grupo")"
-	fi
-      done
-     else
-	error=599
-	txt_salida=$(salida "ERROR" "$error")
-    fi
 
-    txt_salida=${txt_salida::-1}
-    echo "$txt_salida"
-    echo "]"
+       if [ "$error" -lt "500" ]; then
+        if [ "$forzar_borrado" = "TRUE" ]; then
+          /bin/rm -rf $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=536;
+        else
+          /bin/rmdir $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=536;
+        fi
+
+        if [ "$error" -lt "500" ]; then setquota -g "$grupo" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error=531; fi
+        if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$grupo" 2>/dev/null 1>/dev/null || error=532; fi
+      fi
+
+      if [ "$error" -gt "500" ]; then
+        txt_salida="$txt_salida$(salida "ERROR" "$error" "$grupo")"
+      else
+        txt_salida="$txt_salida$(salida "OK" "200" "$grupo")"
+      fi
+    done
+  else
+    error=599
+    txt_salida=$(salida "ERROR" "$error")
+  fi
+
+  txt_salida=${txt_salida::-1}
+  echo "$txt_salida"
+  echo "]"
diff --git a/oscripts/ganesha-del-profes-assignatura b/oscripts/ganesha-del-profes-assignatura
--- a/oscripts/ganesha-del-profes-assignatura
+++ b/oscripts/ganesha-del-profes-assignatura
@@ -34,11 +34,11 @@ asignatura="$2"
 
 salida()
 {
-    echo "{"
-    echo "\"codi\":$2,"
-    echo "\"message\":\"$1\","
-    echo "\"json\": {\"usuario\":\"$3\", \"asignatura\":\"$4\"}" ;
-    echo "},"
+  echo "{"
+  echo "\"codi\":$2,"
+  echo "\"message\":\"$1\","
+  echo "\"json\": {\"usuario\":\"$3\", \"asignatura\":\"$4\"}" ;
+  echo "},"
 }
 
  echo "["
@@ -50,38 +50,35 @@ salida()
 
 # Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són validas de antemano
 
-               if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
-               if [ ! $(getent group "$asignatura") ]; then error=507; fi
+          if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
+          if [ ! $(getent group "$asignatura") ]; then error=507; fi
 
 # Fin control de errores fatales
 
+          if [ -d "$HOME_GANESHA/$asignatura" ]; then /usr/sbin/deluser $usuario $asignatura 2>/dev/null 1>/dev/null || error=521; else error=505; fi
 
-		if [ -d "$HOME_GANESHA/$asignatura" ]; then /usr/sbin/deluser $usuario $asignatura 2>/dev/null 1>/dev/null || error=521; else error=505; fi
-
-		if [ "$error" -lt "500" ] && [ -d "$HOME_GANESHA/$asignatura" ]; then
-		 	cd $HOME_GANESHA"/$asignatura"
-			     for directorio_grupo in  $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do
-				if [ "$(grep $directorio_grupo /etc/group | grep $usuario | wc -l)" -eq "1" ] ; then
-					/usr/sbin/deluser $usuario $directorio_grupo 2>/dev/null 1>/dev/null || error=540;
-				fi
-		     	     done
-		fi
+          if [ "$error" -lt "500" ] && [ -d "$HOME_GANESHA/$asignatura" ]; then
+		 	      cd $HOME_GANESHA"/$asignatura"
+			      for directorio_grupo in  $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do
+              if [ "$(grep $directorio_grupo /etc/group | grep $usuario | wc -l)" -eq "1" ] ; then
+                /usr/sbin/deluser $usuario $directorio_grupo 2>/dev/null 1>/dev/null || error=540;
+              fi
+		     	  done
+		      fi
 
 	        if [ "$error" -gt "500" ]; then
-        	     txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuario" "$asignatura")"
-
+        	  txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuario" "$asignatura")"
 	        else
-	             txt_salida="$txt_salida$(salida "Borrado el profesor \\\"$usuario\\\" de la asignatura \\\"$asignatura\\\"" "200" "$usuario" "$asignatura")"
+	          txt_salida="$txt_salida$(salida "Borrado el profesor \\\"$usuario\\\" de la asignatura \\\"$asignatura\\\"" "200" "$usuario" "$asignatura")"
 	        fi
 
 	      done
-  	else
+  else
 		error=599
 		txt_salida=$(salida "ERROR" "$error")
 	fi
 
-
-    txt_salida=${txt_salida::-1}
-    echo "$txt_salida"
-    echo "]"
+  txt_salida=${txt_salida::-1}
+  echo "$txt_salida"
+  echo "]"
 
