Arreglado bug de borrado de assignatura

diff --git a/oscripts/ganesha-del-assignatura b/oscripts/ganesha-del-assignatura
--- a/oscripts/ganesha-del-assignatura
+++ b/oscripts/ganesha-del-assignatura
@@ -2,16 +2,16 @@
 #
 
 #  Nombre script: ganesha-del-assignatura
-# 
-#  Parámetros de entrada: 
-#   $1=asignatura 
+#
+#  Parámetros de entrada:
+#   $1=asignatura
 #   $2=forzar_borrado
 #
-#  Salida en STDOUT (no STDERR): 
-#    { 
-#    "codi":<codi>, 
-#    "message":"<mensaje>", 
-#    "json": [ { "codi_assignatura":"<codi>" } ] 
+#  Salida en STDOUT (no STDERR):
+#    {
+#    "codi":<codi>,
+#    "message":"<mensaje>",
+#    "json": [ { "codi_assignatura":"<codi>" } ]
 #    }
 #
 #  Operaciones:
@@ -21,7 +21,7 @@
 #	4.- Mostrar codigo de salida correcta o incorrecta según caso.
 #
 #  Codigos de error:
-#	505 - El directorio de la asignatura no existe 
+#	505 - El directorio de la asignatura no existe
 #	507 - El grupo local de la asignatura no existe
 #	530 - Un directorio del grupo de la asignatura no puede borrarse, motivo desconocido
 #	531 - La quota de un grupo de la asignatura no puede borrarse, motivo desconocido
@@ -36,9 +36,9 @@ asignatura="$1"
 forzar_borrado="$2"
 
 salida()
-{ 
-    echo "{" 
-    echo "\"codi\":$2," 
+{
+    echo "{"
+    echo "\"codi\":$2,"
     if [ "$2" -eq "200" ]; then
        echo "\"message\":\"$1\","
     else
@@ -47,7 +47,7 @@ salida()
     fi
     echo "\"json\": [ {\"codi_assignatura\":\"$asignatura\"} ]" ;
     echo "}"
-} 
+}
 
 	error="0"
 
@@ -61,41 +61,41 @@ salida()
 # Fin control de errores fatales
 
 
-          if [ -d "$HOME_GANESHA/$asignatura" ]; then      
+          if [ -d "$HOME_GANESHA/$asignatura" ]; then
 		 cd $HOME_GANESHA"/$asignatura"
 		      for directorio_grupo in $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do
 
 		       error="0"
 
-		       if [ "$forzar_borrado" = "TRUE" ]; then 
-				echo /bin/rm -rf $HOME_GANESHA"/$asignatura/$directorio_grupo" 2>/dev/null 1>/dev/null || error=530;
+		       if [ "$forzar_borrado" = "TRUE" ]; then
+				      /bin/rm -rf $HOME_GANESHA"/$asignatura/$directorio_grupo" 2>/dev/null 1>/dev/null || error=530;
 		       else
-		                /bin/rmdir $HOME_GANESHA"/$asignatura/$directorio_grupo" 2>/dev/null 1>/dev/null || error=530;   
+		          /bin/rmdir $HOME_GANESHA"/$asignatura/$directorio_grupo" 2>/dev/null 1>/dev/null || error=530;
 		       fi
-	
+
 	               if [ "$error" -lt "500" ]; then setquota -g "$directorio_grupo" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error=531; fi
-	
+
 		       if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$directorio_grupo" 2>/dev/null 1>/dev/null || error=532; fi
-			
+
 		     done
 
 		if [ "$error" -lt "500" ]; then setquota -g "$asignatura" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error=533; fi
 
-		if [ "$error" -lt "500" ]; then /bin/rmdir $HOME_GANESHA"/$asignatura" 2>/dev/null 1>/dev/null || error=534; fi 
-		
+		if [ "$error" -lt "500" ]; then /bin/rmdir $HOME_GANESHA"/$asignatura" 2>/dev/null 1>/dev/null || error=534; fi
+
 		if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$asignatura" 2>/dev/null 1>/dev/null || error=535; fi
- 
+
 	   else
 		error=505
 
 	   fi
-	
+
 	else
 		error=599
         fi
 
 	 if [ "$error" -gt "500" ]; then
-             salida "ERROR" "$error" 
+             salida "ERROR" "$error"
           else
  	     salida "Assignatura esborrada correcta i completament." "200"
 	 fi
