Nous codi d'errors implementats

diff --git a/oscripts/ganesha-del-alumnes-grup b/oscripts/ganesha-del-alumnes-grup
--- a/oscripts/ganesha-del-alumnes-grup
+++ b/oscripts/ganesha-del-alumnes-grup
@@ -22,14 +22,13 @@
 #	3.- Mostrar codigo de salida correcta o incorrecta según caso.
 #
 #  Codigos de error:
-#	502 - El grupo "asignatura" no existe
-#	503 - No se ha podido vaciar el grupo
 #	505 - El directorio de la asignatura no existe
 #	506 - El directorio del grupo de la asignatura no existe
 #	507 - El grupo local de la asignatura no existe
 #	508 - El grupo local del grupo de la asignatura no existe
 #	520 - El alumno no puede borrarse del grupo local del grupo de la asignatura, motivo desconocido
 #	521 - El alumno no puede borrarse del grupo local de la asignatura, motivo desconocido
+#	537 - El directorio del grupo de la asingatura no puede vaciarse, motivo desconocido
 #	599 - Faltan parametros
 
 source /usr/local/sbin/ganesha-config.sh
@@ -87,7 +86,12 @@ salida()
 	  done
 	
 	 if [ "$vaciar_grupo" = "TRUE" ] && [ "$error" -lt "500" ]; then
-		if [ -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then /bin/rm -rf "$HOME_GANESHA/$asignatura/$grupo_asignatura/"* || error="503"; fi
+		if [ -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then
+		   /bin/rm -rf "$HOME_GANESHA/$asignatura/$grupo_asignatura/"* 2>/dev/null 1>/dev/null || error=537;
+		   if [ "$error" -gt "500" ]; then
+			 txt_salida="$txt_salida$(salida "ERROR" "$error" "$usuarios" "$asignatura" "$grupo_asignatura")"
+		   fi
+		fi
  	 fi
 
   	else
diff --git a/oscripts/ganesha-del-assignatura b/oscripts/ganesha-del-assignatura
--- a/oscripts/ganesha-del-assignatura
+++ b/oscripts/ganesha-del-assignatura
@@ -5,8 +5,7 @@
 # 
 #  Parámetros de entrada: 
 #   $1=asignatura 
-##   $2=quota
-#   $3=forzar_borrado
+#   $2=forzar_borrado
 #
 #  Salida en STDOUT (no STDERR): 
 #    { 
@@ -22,12 +21,15 @@
 #	4.- Mostrar codigo de salida correcta o incorrecta según caso.
 #
 #  Codigos de error:
-#	501 - El directorio no se puede crear (1.- El directorio ya existe. 2.- Permiso denegado). 
-#	502 - El grupo no se puede crear. (1.- El grupo ya existe. 2.- Permiso denegado).
-#	503 - No se han podido cambiar los permisos. (1.- El directorio o grupo no existe. 2.- Permiso denegado)
-##	504 - No se ha podido asignar la quota
-#	505 - El directorio de la asignatura principal no existe
-#	510 - Faltan parámetros
+#	505 - El directorio de la asignatura no existe 
+#	507 - El grupo local de la asignatura no existe
+#	530 - Un directorio del grupo de la asignatura no puede borrarse, motivo desconocido
+#	531 - La quota de un grupo de la asignatura no puede borrarse, motivo desconocido
+#	532 - El grupo local de un grupo de la asignatura no puede borrarse, motivo desconocido
+#	533 - La quota de la asignatura no puede borrarse, motivo desconocido
+#	534 - El directorio de la asignatura no puede borrarse, motivo desconocido
+#	535 - El grupo local de la asignatura no puede borrarse, motivo desconocido
+#	599 - Faltan parámetros
 
 source /usr/local/sbin/ganesha-config.sh
 asignatura="$1"
@@ -37,7 +39,12 @@ salida()
 { 
     echo "{" 
     echo "\"codi\":$2," 
-    echo "\"message\":\"$1\"," 
+    if [ "$2" -eq "200" ]; then
+       echo "\"message\":\"$1\","
+    else
+       codigo_error="codigo_$2"
+       echo "\"message\":\"${!codigo_error}\","
+    fi
     echo "\"json\": [ {\"codi_assignatura\":\"$asignatura\"} ]" ;
     echo "}"
 } 
@@ -46,42 +53,45 @@ salida()
 
 	if [ $asignatura ]; then
 
+# Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són válidas de antemano
+
+          if [ ! -d "$HOME_GANESHA/$asignatura" ]; then salida "ERROR" "505"; exit ; fi
+          if [ ! $(getent group "$asignatura") ]; then salida "ERROR" "507"; exit; fi
+
+# Fin control de errores fatales
+
+
           if [ -d "$HOME_GANESHA/$asignatura" ]; then      
 		 cd $HOME_GANESHA"/$asignatura"
 		      for directorio_grupo in $(find ./ -maxdepth 1 -mindepth 1 -type d -printf '%f\n') ; do
 
 		       error="0"
 
-		       if [ ! -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then 
-				echo el directorio no exite
-				exit
- 		       fi
-
 		       if [ "$forzar_borrado" = "TRUE" ]; then 
-				echo /bin/rm -rf $HOME_GANESHA"/$asignatura/$directorio_grupo" 2>/dev/null 1>/dev/null || error="501";
+				echo /bin/rm -rf $HOME_GANESHA"/$asignatura/$directorio_grupo" 2>/dev/null 1>/dev/null || error=530;
 		       else
-		                /bin/rmdir $HOME_GANESHA"/$asignatura/$directorio_grupo" 2>/dev/null 1>/dev/null || error="501";   
+		                /bin/rmdir $HOME_GANESHA"/$asignatura/$directorio_grupo" 2>/dev/null 1>/dev/null || error=530;   
 		       fi
 	
-	               if [ "$error" -lt "500" ]; then setquota -g "$directorio_grupo" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error="504"; fi
+	               if [ "$error" -lt "500" ]; then setquota -g "$directorio_grupo" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error=531; fi
 	
-		       if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$directorio_grupo" 2>/dev/null 1>/dev/null || error="502"; fi
+		       if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$directorio_grupo" 2>/dev/null 1>/dev/null || error=532; fi
 			
 		     done
 
-		if [ "$error" -lt "500" ]; then setquota -g "$asignatura" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error="504"; fi
+		if [ "$error" -lt "500" ]; then setquota -g "$asignatura" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error=533; fi
 
-		if [ "$error" -lt "500" ]; then /bin/rmdir $HOME_GANESHA"/$asignatura" 2>/dev/null 1>/dev/null || error="501"; fi 
+		if [ "$error" -lt "500" ]; then /bin/rmdir $HOME_GANESHA"/$asignatura" 2>/dev/null 1>/dev/null || error=534; fi 
 		
-		if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$asignatura" 2>/dev/null 1>/dev/null || error="503"; fi
+		if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$asignatura" 2>/dev/null 1>/dev/null || error=535; fi
  
 	   else
-		error="505"
+		error=505
 
 	   fi
 	
 	else
-		error="510"
+		error=599
         fi
 
 	 if [ "$error" -gt "500" ]; then
diff --git a/oscripts/ganesha-del-grups b/oscripts/ganesha-del-grups
--- a/oscripts/ganesha-del-grups
+++ b/oscripts/ganesha-del-grups
@@ -34,9 +34,14 @@
 #	3.- Mostrar codigo de salida correcta o incorrecta según caso.
 #
 #  Codigos de error:
-#       501 - El directorio no se puede borrar (1.- El directorio no existe. 2.- Permiso denegado. 3.- El directorio no está vacío).
-#       502 - El grupo no se borrar. (1.- El grupo no existe. 2.- Permiso denegado).
-#	510 - Faltan parámetros 
+#       505 - El directorio de la asignatura no existe
+#       506 - El directorio del grupo de la asignatura no existe
+#       507 - El grupo local de la asignatura no existe
+#       508 - El grupo local del grupo de la asignatura no existe
+#       531 - La quota de un grupo de la asignatura no puede borrarse, motivo desconocido
+#       532 - El grupo local de un grupo de la asignatura no puede borrarse, motivo desconocido
+#	536 - El directorio del grupo de la asignatura no puede borrarse, motivo desconocido
+#       599 - Faltan parámetros
 
 source /usr/local/sbin/ganesha-config.sh
 asignatura="$1"
@@ -47,8 +52,13 @@ salida()
 { 
     echo "{" 
     echo "\"codi\":$2," 
-    echo "\"message\":\"$1\"," 
-    echo "\"json\": {\"nomgrup\":\"$3\"}" ; 
+    if [ "$2" -eq "200" ]; then
+       echo "\"message\":\"$1\","
+    else
+       codigo_error="codigo_$2"
+       echo "\"message\":\"${!codigo_error}\","
+    fi
+    echo "\"json\": {\"asignatura:\":\"$asignatura\",\"nomgrup\":\"$3\"}" ; 
     echo "},"
 } 
 
@@ -58,23 +68,37 @@ salida()
 
     for grupo in $grupos_asignatura
       do
-	error="0" 
-	if [ "$forzar_borrado" = "TRUE" ]; then 
-		/bin/rm -rf $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error="501";
-	  else
-		/bin/rmdir $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error="501";	
-	 fi
 
-	if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$grupo" 2>/dev/null 1>/dev/null || error="502"; fi
+       error=0
+
+# Control de errores fatales: Es para evitar acciones intermedias si las condiciones necesarias conocidas no són validas de antemano
+
+       if [ ! -d "$HOME_GANESHA/$asignatura" ]; then error=505; fi
+       if [ ! -d "$HOME_GANESHA/$asignatura/$grupo_asignatura" ]; then error=506; fi
+       if [ ! $(getent group "$asignatura") ]; then error=507; fi
+       if [ ! $(getent group "$grupo") ]; then error=508; fi
+
+# Fin control de errores fatales
+       
+       if [ "$error" -lt "500" ]; then
+	if [ "$forzar_borrado" = "TRUE" ]; then 
+		/bin/rm -rf $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=536;
+	  else
+		/bin/rmdir $HOME_GANESHA"/$asignatura/$grupo" 2>/dev/null 1>/dev/null || error=536;	
+	fi
+	
+	if [ "$error" -lt "500" ]; then setquota -g "$grupo" 0 0 0 0 $HOME_GANESHA"/" 2>/dev/null 1>/dev/null || error=531; fi
+	if [ "$error" -lt "500" ]; then /usr/sbin/delgroup "$grupo" 2>/dev/null 1>/dev/null || error=532; fi
+       fi
 	
 	if [ "$error" -gt "500" ]; then
 	     txt_salida="$txt_salida$(salida "ERROR" "$error" "$grupo")"
 	  else 
 	     txt_salida="$txt_salida$(salida "OK" "200" "$grupo")"
-	  fi
+	fi
       done
      else
-	error="510"
+	error=599
 	txt_salida=$(salida "ERROR" "$error")
     fi
 
